### ISSUE TITLE
Schedule Rocketchat upgrade

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#184] opened 2020-03-17 17:46 UTC
- test on moving to cloud cluster
- version 3 is available with several fix: https://github.com/RocketChat/Rocket.Chat/issues/16296#issuecomment-599914331

**Comment by ShellyXueHan** [comment] 2020-05-06 18:50
blocked: waiting for suitable cluster

**Comment by lukegonis** [comment] 2020-08-05 18:46
Closing this issue as it is a duplicate of issue 209

**Closed by lukegonis** 2020-08-05 18:46 UTC
Labels: rocketchat
