### ISSUE TITLE
Figure out how to integrate with Platform Status to show a real live button and the real live status.

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2441] opened 2022-04-05 22:24 UTC
**Describe the issue**
Figure out how to integrate with Platform Status to show a real live button, not an image. Right now on the test site, the Platform Status green button is just a static button that we put in for testing and as a placeholder. We will need a real-live button so that it accurately reflects the platform status.

Also, we need to integrate it into the [platform status page](https://platform-services-dev.apps.silver.devops.gov.bc.ca/our-services-in-private-cloud-paas/platform-status-for-private-cloud-paas/) so people don't have to leave the site to see the status.

**Additional context**
A screenshot of what is on the home page.
![image.png](https://images.zenhubusercontent.com/619e7c0917f0b96bbcf6d42f/935ef5ee-08df-4039-a306-1808b2fc6d15)

**Definition of done**
- [ ] Create a reusable block that we can put on the site wherever it's needed.
- [ ] The platform status page has the status table integrated.

**Comment by ty2k** [comment] 2022-04-06 17:47
Duplicate of #2339. I'm going to close this one and keep the original ticket.

**Closed by ty2k** 2022-04-06 17:47 UTC
Labels: app-development
