### ISSUE TITLE
SysDig: Capacity Dasboard

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#295] opened 2020-04-24 21:26 UTC
https://trello.com/c/nLKjabpy/103-sysdig-capacity-dasboard

See screenshot. This is focused at App nodes, and would be nice to see over time

**Comment by jefkel** [comment] 2020-07-30 20:23
Closing as duplicate of #296

**Closed by jefkel** 2020-07-30 20:23 UTC
Labels: Infrastructure
