### ISSUE TITLE
Add NSX-T KLAB 2 cluster to CCM

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1328] opened 2021-06-22 21:47 UTC
We need to test the ability of the NSX-T enabled cluster to be upgraded as part of the standard maintenance on the Openshift 4 Platform. For that purpose, we need to intregrated it into our CCM model so that when we run upgrades across the OCP 4 clusters next time, it will be ugpraded in the same fashion as other LAB clusters.

**Comment by StevenBarre** [comment] 2021-07-23 18:22
Closing as duplicate of #1347

**Closed by StevenBarre** 2021-07-23 18:22 UTC
Labels: medium priority, ops and shared services
