### ISSUE TITLE
Make non-clickable text fields a plain text

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3740] opened 2023-03-23 22:23 UTC
**Describe the issue**

**Rational/Why**

**Additional Context** 

**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**

**Comment by funtigr** [comment] 2023-04-13 22:00
Duplicate of a task: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcgov/platform-services-registry/869

**Closed by funtigr** 2023-04-13 22:00 UTC
Labels: *team/ app development*
