### ISSUE TITLE
Information Architecture and Content Review

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1424] opened 2021-07-21 22:32 UTC
**Describe the issue**
The community is looking for us to improve private cloud technical documentation and onboarding content, focusing on quality, organization and find-ability.

**Additional context**
The 2021/2022 Product Roadmap is committing to the following three items in Q2 through Q3 as high to high/medium priorities.  This EPIC is looking to begin the journey of tackling these three items, which will most likely become EPICs themselves.

- HIGH - Improve Platform technical documentation content, quality and organization
- HIGH/MED - Improve Platform onboarding experience + create a clearer journey guide
- MED - Make content in DevHub easier to find / more intelligent search 

**Definition of done**

- [ ] MVP: A content and information architecture strategy
- [ ] Plan with multiple EPICs to complement actionable items including community research, engagement, required resources, new web properties, technical solutions.

**Comment by mitovskaol** [comment] 2021-07-23 22:19
@juhewitt Is this duplicate of [#1164](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1164)

**Comment by juhewitt** [comment] 2021-07-23 22:34
No @mitovskaol, they are different work items.  Correlated, but different.

**Closed** 2022-05-12 18:31 UTC
Labels: Epic, community, ops and shared services, service-design
