### ISSUE TITLE
Fix MCS_AlertManager_Volume Nagios metric

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3110] opened 2022-10-03 17:21 UTC
**Describe the issue**
The Nagios graph for MCS_AlertManager_Volume appears to have no data anymore.

https://github.com/bcgov-c/platform-tools/blob/989fad82920296c5c1e376475115fc416c15332a/nagios/runner/project/roles/nagios/tasks/long-term-metrics.yaml#L502

**What is the Value/Impact?**
No graph showing long term changes in usage

**What is the plan? How will this get completed?**
- Investigate the prom query used to get the data.
- Test a fix in lab
- Roll out updated Nagios to all clusters

**Identify any dependencies**
None

**Definition of done**
All clusters have working MCS_AlertManager_Volume graph in Nagios

**Comment by tmorik** [comment] 2022-12-14 20:28
It seems those nagios graphs had recovered and resume collecting metrics again on Dec 5th, 3:50 PM ish.

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/e73ab674-1f20-429e-83ae-f3dd5974130a) 

The reason is still unknown. I will investigate it.

**Comment by tmorik** [comment] 2022-12-14 20:34
It seems Prometheus was OK past 2 weeks (include the blank period in nagios):

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/c1359735-57b0-4fce-9137-26144d55a6fa)

```query
max(kubelet_volume_stats_capacity_bytes{namespace=~"openshift-monitoring|openshift-logging|openshift-image-registry"}) by (namespace,persistentvolumeclaim)
```

**Comment by tmorik** [comment] 2022-12-14 21:09
Not only this alert manager's graph (metrics), but also the other graphs on the passive nagios(nagios.advsol.tech) had been reset(?) and cannot go further beyond the Dec 5th.

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/d54835b7-d7ca-4a5f-9e37-11d755eefe7b)

This is Gold's graph.

**Comment by tmorik** [comment] 2022-12-14 21:09
I will open up a ticket to SAM team.

**Comment by tmorik** [comment] 2022-12-14 21:10
In the meantime, the alert manager's graphs are came back and match with the result of Prom query.

**Comment by tmorik** [comment] 2022-12-14 21:26
An internal AdvSol ticket has been opened with the SAM team to investigate this issue. (IMS0003327)

**Comment by tmorik** [comment] 2022-12-15 17:04
Confirmed `MCS_AlertManager_Volume Nagios metric` has been collected and showed up in the graph in the nagios.  I will close this ticket. The issue of `missing data before Dec 5th` will still be investigated by ADsol SAM team under advsol's Hub ticket (INC0073910).

**Closed by tmorik** 2022-12-15 17:04 UTC
Labels: team/DXC, ops and shared services
