### ISSUE TITLE
Migrate Pathfinder ESX cluster to Azure Stack hardware

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#519] opened 2020-06-18 20:12 UTC
Hosting Branch has offered to give us 3 physical hosts so we can get access to more compute power for the OCP VMs. Ticket to track progress and timelines.

**Comment by DanDeane** [comment] 2020-06-23 14:00
AFAIK at this point the hosts are:
Dual Processor
768Gb -> 1Tb or RAM
>5Tb of internal HDD and SSD disks.
10Gb networking.
I am working on the plan to build these out with vsphere and vsan enabled.

**Comment by mitovskaol** [comment] 2020-08-27 20:28
Hardware will start to get moved on Aug 31 starting with app nodes.

**Comment by wmhutchison** [comment] 2020-09-03 20:17
Started work on this, but ran into a hurdle on the first APP node. Still troubleshooting, and starting to look like it may be related to F5 load balancer issues. Today will setup suitable tcpdump sessions and open an incident to Network for follow-up.

**Comment by wmhutchison** [comment] 2020-09-10 19:32
Internal incident ticket INC0040682 opened with DXC Network staff to help troubleshoot, since the symptom on hand appears to be related to connectivity from the F5 via the api-int.klab.devops.gov.bc.ca URL, which is balanced between the three master nodes.

Additional testing revealed that this issue is not unique to the new ESXi cluster. We attempted to re-image the original APP-01 VM on the original ESXi cluster, and that failed as well.

Final testing possible without further input from Network was our using a software firewall trick via iptables where we block the F5 from speaking on the target port to a master node, thus forcing the F5 to not send traffic to said master node. We used this to iterate through forcing 100% of the traffic to each of the master nodes while blocking the other two to see if that improved matters - it did not.

Official next step was recently initiated by the DXC Network team lead who has been kept in the loop, and has assigned a representative from his team to work with William regarding screen-sharing and take troubleshooting of this matter forward. Reaching out to said rep after updating this ticket.

**Comment by wmhutchison** [comment] 2020-09-17 18:25
A major blocker was removed after discovering that the cause of the original blockage was a default 10s timeout for the HTTPS config fetch (test on UTIL averages 17s each time).

Playbooks were updated to ensure new ignition files have the recommended 2m timeout.

A smaller blockage was experienced next due to discovering Storage VLAN wasn't working on the new ESXi cluster. Dan Deane took this on with Network, and was resolved shortly after.

**Comment by wmhutchison** [comment] 2020-09-17 18:27
Current state is now having the new APP-01 and APP-02 nodes bootstrapped onto the new cluster, doing some final validation on those nodes before proceeding with additional APP node work.

Also will coordinate with Justin Pye regarding some deliverables involving testing Openshift upgrade in KLAB while Aporeto is enabled. Willl make sure we're not in the middle of any node migration during that test.

**Comment by wmhutchison** [comment] 2020-09-23 20:39
Work is now complete - all VMs migrated and RAM upgraded to requested amount per https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/346 . Closing this off.

**Closed by wmhutchison** 2020-09-23 20:39 UTC
Labels: Infrastructure
