### ISSUE TITLE
Resolve docker-registry redeploy failing (OCP 3.11)

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#276] opened 2020-04-24 21:26 UTC
https://trello.com/c/d1uspkdo/139-resolve-docker-registry-redeploy-failing-ocp-311

The docker-registry is intermittently failing a redeploy.

Impact:
Quarterly Registry Prune switches the registry to Read-Only, runs it's prune and then switches the registry back to read-write.
When the redeploy fails, it can leave the docker-registry in read-only mode with no fall-back or alerting.

Quick fix is to add a monitor to alert if the registry is in read-only mode to get manual attention faster

Identify other options to resolve automatically where possible.

**Comment by wmhutchison** [comment] 2020-05-07 16:19
Changes to monitoring regarding registry pods in Read only state previously implemented/unit-tested. Said changes received their first actual run on April 1st when the quarterly hard prune kicked in. During the time of the actual pruning, a WARN email was sent (no escalation to on-call) stating that registry pods were in read-only mode but a valid hard prune operation was still proceeding. Since Aporeto is no longer active in PROD, there was no issues for the automation that switches the registry pods back to read/write, and thus no on-call intervention was required.

This confirmation of the above monitoring changes coupled with the ultimate root cause for preventing registry pod redeployments (Aporeto) being no longer present in PROD, this issue can be closed as Done.

**Closed by wmhutchison** 2020-05-07 16:19 UTC
Labels: Infrastructure, medium priority
